# FSL Distro for Wayland with XWayland.

require conf/distro/include/fsl-base.inc

DISTRO = "fsl-xwayland"
DISTRO_NAME = "FSL Wayland with XWayland"

# Define Init System
INIT_MANAGER = "systemd"

include conf/fragments/bsp/nxp.conf
include conf/fragments/graphics/xwayland.conf
