# FSLC Distro for Wayland.

require conf/distro/include/fslc-base.inc

DISTRO = "fslc-wayland"
DISTRO_NAME = "FSLC Wayland"

# Define Init System
INIT_MANAGER = "systemd"

include conf/fragments/bsp/fslc.conf
include conf/fragments/graphics/wayland.conf
