# FSLC Distro for FrameBuffer graphical backend.

require conf/distro/include/fslc-base.inc

DISTRO = "fslc-framebuffer"
DISTRO_NAME = "FSLC FrameBuffer"

include conf/fragments/bsp/fslc.conf
include conf/fragments/graphics/framebuffer.conf
