# FSLC Distro for Wayland with XWayland.

require conf/distro/include/fslc-base.inc

DISTRO = "fslc-xwayland"
DISTRO_NAME = "FSLC Wayland with XWayland"

# Define Init System
INIT_MANAGER = "systemd"

include conf/fragments/bsp/fslc.conf
include conf/fragments/graphics/xwayland.conf
