# FSLC Distro for X11 without wayland.

require conf/distro/include/fslc-base.inc

DISTRO = "fslc-x11"
DISTRO_NAME = "FSLC X11"

include conf/fragments/bsp/fslc.conf
include conf/fragments/graphics/x11.conf
